version: "2"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    volumes: 
      - /Users/mrshi/db:/data/db
    ports:
      - "27017:27017"
